on:
  # but only for the main branch
  push:
    branches:
      - main

name: Mirror
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-18.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - uses: spyoungtech/mirror-action@master
        with:
          REMOTE: 'https://gitlab.com/chenfengjin/xvm1.git'

          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"

